name: flutter_getit
description: Integrating with 'get_it,' it efficiently manages Flutter project
  dependencies, providing robust page control, route management, and module
  flexibility
version: 2.1.0-beta.1
repository: https://github.com/rodrigorahman/getit_flutter
issue_tracker: https://github.com/rodrigorahman/getit_flutter/issues
tags:
  - dependency
  - package
  - version
  - pubspec
  - management
  - dev_dependencies
  - dependencies
  - pub.dev
  - routes
  - navigation
  - modules
  - modularity

topics:
  - dependency-injection
  - di
  - injection
  - router
  - routing

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.7

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
